# yaml-language-server: $schema=../config.schema.json

template: graphinx/templates/default

schema:
  static: ./schema.graphql

branding:
  logo:
    dark: https://churros.inpt.fr/logo-masked.png
    light: /logo-masked-dark.png
  name: Churros API

pages: docs/
static: docs/static

environment:
  PUBLIC_API_URL: https://churros.app/graphql
  PUBLIC_API_URL_DISPLAY: churros.app/graphql
  PUBLIC_API_WEBSOCKET_URL: https://churros.app/graphql
  CURRENT_COMMIT: dev
  CURRENT_VERSION: "0.1.0"
  CURRENT_COMMIT_SHORT: dev
  PUBLIC_AUTH_TYPE: OAuth # available: OAuth (PKCE flow), OpenID, UserPassword, Token, None (default)
  PUBLIC_AUTH_HEADER: Bearer # available: Bearer (for all AUTH_TYPEs), Basic (for UserPassword, takes the base64 of the form `username:password`), plain (for all types, just puts the token as is)
  PUBLIC_OAUTH_AUTHORIZE_URL: https://authorization-server.com/authorize
  PUBLIC_OAUTH_TOKEN_URL: https://authorization-server.com/token
  PUBLIC_OAUTH_CLIENT_ID: 4xDFlLfJifhWDutqEcZiEbHY
  # No client secret, as we use PKCE. This is a static website, env vars are baked in!

modules:
  docs: src/modules/[module]/README.md
  icons: src/modules/[module]/icon.svg
  fallback: global
  filesystem:
    - src/modules/[module]/resolvers/[parent].[fieldname].ts
    - src/modules/[module]/types/[typename].ts
  mapping: 
    ID: global
    Node: global
    PageInfo: global
    Error: global
    ErrorInterface: global
    ZodFieldError: global
    NotFoundError: global
    # FIXME: Graphinx cannot infer when success datatype is String
    EventBookingsCsv{Result,Success}: ticketing
  order:
    - global
    - users
    - groups
    - posts
    - events
    - ticketing
    - shop
    - forms
    - documents
    - themes
    - pictures
    - profiles
    - notifications
    - services
    - bar-weeks
    - student-associations
    - pages
    - schools
    - curriculum
    - comments
    - reactions
    - links
    - announcements
    - payments
    - gitlab
    - changelogs
    - logs
    - health-checks

description: ./homepage.md

footer: |
  <p>
    Churros API, version %$CURRENT_VERSION% (at
    <a href="https://git.inpt.fr/inp-net/churros/-/commit/%$CURRENT_COMMIT%">
      <code class="no-color">%$CURRENT_COMMIT_SHORT%</code></a
    >)
  </p>
  <a class="net7" href="https://net7.dev">
    Made with <span style:color="red"><strong>&lt;3</strong></span> by
    <img data-dark src="https://churros.inpt.fr/storage/groups/dark/net7-n7.png" alt="net7" />
    <img data-light src="https://churros.inpt.fr/storage/groups/net7-n7.png" alt="net7" />
  </a>

  <style>
    .net7 {
      display: flex;
      flex-wrap: wrap;
      column-gap: 1ch;
      align-items: center;
      justify-content: center;
      margin-top: 5rem;
      font-family: 'Space Mono', monospace;
      color: var(--fg);
      text-decoration: none;
      border-radius: 2rem;
      transition: box-shadow 0.2s ease;
    }

    .net7:hover,
    .net7:focus-visible {
      box-shadow: 0 0 50px 3px color-mix(in oklab, var(--fg) 15%, var(--shadow));
    }

    .net7 img {
      width: 100px;
      margin-left: 1em;
    }

    [data-theme=light] .net7 img[data-dark] {
      display: none;
    }

    [data-theme=dark] .net7 img[data-light] {
      display: none;
    }
  </style>
