# yaml-language-server: $schema=../config.schema.json

schema:
  introspection:
    url: https://churros.inpt.fr/graphql
    headers:
      User-Agent: Narasimha

branding:
  logo: https://churros.inpt.fr/logo.svg
  name: Churros API

pages: ./packages/api/docs/pages
static: ./packages/api/docs/static

footer: |
  <p>
    Churros API, version %$CURRENT_VERSION% (at
    <a href="https://git.inpt.fr/inp-net/churros/-/commit/%$CURRENT_COMMIT%">
      <code class="no-color">%$CURRENT_COMMIT_SHORT%</code></a
    >)
  </p>
  <a class="net7" href="https://net7.dev"
    >Made with <span style:color="red"><strong>&lt;3</strong></span> by
    <img src="https://churros.inpt.fr/storage/groups/dark/net7-n7.png" alt="net7" /></a
  >

  <style>
    .net7 {
      display: flex;
      flex-wrap: wrap;
      column-gap: 1ch;
      align-items: center;
      justify-content: center;
      margin-top: 5rem;
      font-family: 'Space Mono', monospace;
      color: var(--fg);
      text-decoration: none;
      border-radius: 2rem;
      transition: box-shadow 0.2s ease;
    }

    .net7:hover,
    .net7:focus-visible {
      box-shadow: 0 0 50px 3px color-mix(in oklab, var(--fg) 15%, var(--shadow));
    }

    .net7 img {
      width: 100px;
      margin-left: 1em;
    }
  </style>

modules:
  index:
    title: Index
    description: Le schéma GraphQL entier
  filesystem:
    intro: ./packages/api/src/modules/%module%/README.md
    icon: ./packages/api/src/modules/%module%/icon.svg
    order:
      - global
      - users
      - groups
      - posts
      - events
      - ticketing
      - shop
      - forms
      - documents
      - notifications
      - services
      - bar-weeks
      - student-associations
      - pages
      - schools
      - curriculum
      - comments
      - reactions
      - links
      - oauth
      - announcements
      - payments
      - gitlab
      - changelogs
      - logs
      - health-checks
    items:
      - files: ./packages/api/src/modules/%module%/{resolvers,types}/*.ts
        match: "builder.((query|mutation)Field|\\w+Type)\\('(?<name>[^']+)'\\)"
        contribution: https://git.inpt.fr/inp-net/churros/-/blob/main/packages/api/src/modules/%module%/
