#!/usr/bin/env node
import { program } from "commander"
import { version } from "../package.json"
import yaml from "yaml"
import { Convert, type Config } from "./config.js"
import {
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
  renameSync,
} from "node:fs"
import { transformStrings } from "./utils.js"
import { replacePlaceholders } from "./placeholders.js"
import degit from "degit"
import { rimrafSync } from "rimraf"
import type { BuiltData } from "./built-data.js"
import { getAllModules, getAllResolvers } from "./modules.js"
import { loadSchema } from "./schema-loader.js"
import path from "node:path"

program
  .version(version)
  .option(
    "-c, --config <path>",
    "Path to the configuration file",
    ".graphinx.yaml"
  )
  .option("-k, --keep", "Keep the build area after building", false)
  .parse(process.argv)

const options = program.opts()

if (!existsSync(options.config)) {
  console.error(`Config file not found: ${options.config}`)
  process.exit(1)
}

const { modules, ...restOfConfig } = Convert.toConfig(
  JSON.stringify(yaml.parse(readFileSync(options.config, "utf-8")))
)

const config: Config = {
  ...transformStrings(restOfConfig, replacePlaceholders),
  modules: {
    ...modules,
    index: transformStrings(modules?.index, replacePlaceholders),
  },
}

const BUILD_AREA_DIRECTORY = ".build"

if (!options.keep && existsSync(BUILD_AREA_DIRECTORY))
  rimrafSync(BUILD_AREA_DIRECTORY)

if (!existsSync(BUILD_AREA_DIRECTORY)) {
  const emitter = degit("ewen-lbh/graphinx/packages/template#main", {
    cache: true,
    force: true,
    verbose: true,
  })

  emitter.on("info", console.info)
  await emitter.clone(BUILD_AREA_DIRECTORY)
}

const schema = await loadSchema(config)
console.log(`Loaded ${Object.keys(schema.types).length} types from schema`)

const resolvers = await getAllResolvers(schema, config)

const builtData: BuiltData = {
  modules: await getAllModules(schema, config, resolvers),
  resolvers,
  schema,
  config,
}

writeFileSync(
  path.join(BUILD_AREA_DIRECTORY, "src/lib/data.generated.ts"),
  `// This file is generated by Graphinx. Do not edit.
import type { BuiltData } from 'graphinx';
export const data: BuiltData = ${JSON.stringify(builtData, null, 2)};`
)

console.log(config)

if (!options.keep) rimrafSync(BUILD_AREA_DIRECTORY)
