config -> each module

each module: {
    module name -> create all matchers
    glob filepaths -> contents -> ast-grep -> create all matchers
    contents -> create all matchers
}

each module.create all matchers -> each item.try match

each item: {
    try match
}
